// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlTLXmjp-9u5OBEFKJdCBy8dtFQyTnOUI',
    appId: '1:835873657637:web:b19f2c95e94484bde3c0cc',
    messagingSenderId: '835873657637',
    projectId: 'doctor-app-92091',
    authDomain: 'doctor-app-92091.firebaseapp.com',
    storageBucket: 'doctor-app-92091.firebasestorage.app',
    measurementId: 'G-39V71F1HH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjZicGEbLIBnFBhhsPMkCHbpZY1qeBNds',
    appId: '1:835873657637:android:cae1bdffc3a4ac83e3c0cc',
    messagingSenderId: '835873657637',
    projectId: 'doctor-app-92091',
    storageBucket: 'doctor-app-92091.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBELwtpfI9pvVOFnIba-J8BFFgdnPULHq0',
    appId: '1:835873657637:ios:533367cb9abb4fa6e3c0cc',
    messagingSenderId: '835873657637',
    projectId: 'doctor-app-92091',
    storageBucket: 'doctor-app-92091.firebasestorage.app',
    iosBundleId: 'com.example.Doctorapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBELwtpfI9pvVOFnIba-J8BFFgdnPULHq0',
    appId: '1:835873657637:ios:533367cb9abb4fa6e3c0cc',
    messagingSenderId: '835873657637',
    projectId: 'doctor-app-92091',
    storageBucket: 'doctor-app-92091.firebasestorage.app',
    iosBundleId: 'com.example.Doctorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlTLXmjp-9u5OBEFKJdCBy8dtFQyTnOUI',
    appId: '1:835873657637:web:daab7d84615ff54ae3c0cc',
    messagingSenderId: '835873657637',
    projectId: 'doctor-app-92091',
    authDomain: 'doctor-app-92091.firebaseapp.com',
    storageBucket: 'doctor-app-92091.firebasestorage.app',
    measurementId: 'G-RWCVK9E3EP',
  );
}
